vich_uploader:
    db_driver: orm

    mappings:
        cars_images:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/uploads/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
